name: Bug Report
description: Erstelle ein Bug-Ticket
title: "[Bug]: "
labels: ["bug"]
assignees:
  - njarowsky
body:
  - type: markdown
    attributes:
      value: |
        Vielen Dank, dass Sie sich die Zeit nehmen, diesen Fehlerbericht auszufüllen!
  - type: input
    id: contact
    attributes:
      label: Kontaktinformationen
      description: Wie können wir Sie erreichen, falls wir weitere Informationen benötigen?
      placeholder: z. B. email@beispiel.de
    validations:
      required: false
  - type: textarea
    id: what_happened
    attributes:
      label: Was ist passiert?
      description: Beschreiben Sie auch, was Sie erwartet hätten.
      placeholder: Beschreiben Sie, was Sie sehen!
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Welche Version unserer Software verwenden Sie?
      options:
        - 1.0.0 (Standard)
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: browsers
    attributes:
      label: Browser
      description: In welchen Browsern tritt das Problem auf? (Mehrfachauswahl möglich)
      options:
        - label: Firefox
        - label: Chrome
        - label: Safari
        - label: Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevante Log-Ausgaben
      description: Bitte fügen Sie relevante Log-Ausgaben oder Fehlermeldungen hier ein.
      render: shell
